# Generated by Django 4.1.2 on 2022-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_remove_profile_friend_profile_friend'),
        ('posts', '0003_remove_post_like_post_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='like_post', to='authenticate.profile'),
        ),
    ]
