# Generated by Django 4.1.2 on 2022-10-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_profile_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.profile'),
        ),
    ]
