# Generated by Django 4.1.2 on 2022-10-31 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_alter_profile_user"),
        ("authenticate", "0004_alter_profile_friend"),
    ]

    operations = []
